from __future__ import annotations
import os
from pathlib import Path
import streamlit as st

APP_NAME = "Statix"
ROOT = Path(__file__).resolve().parents[1]
ARTIFACT_DIR = ROOT / "artifacts"
MODEL_PATH = ARTIFACT_DIR / "statix_model.joblib"
MODEL_META_PATH = ARTIFACT_DIR / "model_meta.json"
SEQUENCE_LENGTH = 64
SCANNER_PREFILTER_LIMIT = 100
SCANNER_RESULT_LIMIT = 20
HORIZON = 5
MAX_SCAN = 2000
QUOTE_TTL = 15
HISTORY_TTL = 60
SEARCH_TTL = 600
SCANNER_STALE_MINUTES = 30

LANGUAGES = {
    "English":"en", "Français":"fr", "Español":"es", "Italiano":"it",
    "Deutsch":"de", "中文":"zh", "日本語":"ja", "한국어":"ko", "Português":"pt",
}

TEXT = {
"en": {"home":"Home","stocks":"Stocks","discover":"Discover","settings":"Settings","market_pulse":"Live market pulse","top_stocks":"Top stocks","discover_short":"Discover","watch_suggestions":"From your watchlist","search":"Search stocks","watchlist":"Watchlist","provider":"Provider","language":"Language","refresh":"Refresh","analyze":"Analyze","watch":"Watch","remove":"Remove","no_results":"No securities found.","scanner":"Scanner & recommendations","queue":"Run scanner","latest":"Latest scan","confidence":"Confidence","reliability":"Reliability","expected":"Expected 5D return","price":"Price","change":"Day change","save":"Save settings","identity":"Identity","data_source":"Data source","auto":"Automatic fallback","model":"Prediction model","no_model":"Train and install the model before predictions are available."},
"fr": {"home":"Accueil","stocks":"Actions","discover":"Découvrir","settings":"Paramètres","market_pulse":"Marché en direct","top_stocks":"Actions populaires","discover_short":"Découvrir","watch_suggestions":"Depuis votre liste","search":"Rechercher des actions","watchlist":"Liste de suivi","provider":"Fournisseur","language":"Langue","refresh":"Actualiser","analyze":"Analyser","watch":"Suivre","remove":"Retirer","no_results":"Aucun titre trouvé.","scanner":"Scanner et recommandations","queue":"Lancer le scanner","latest":"Dernier scan","confidence":"Confiance","reliability":"Fiabilité","expected":"Rendement prévu à 5 jours","price":"Prix","change":"Variation du jour","save":"Enregistrer","identity":"Identité","data_source":"Source des données","auto":"Repli automatique","model":"Modèle de prévision","no_model":"Entraînez et installez le modèle avant les prévisions."},
"es": {"home":"Inicio","stocks":"Acciones","discover":"Descubrir","settings":"Ajustes","market_pulse":"Mercado en vivo","top_stocks":"Acciones destacadas","discover_short":"Descubrir","watch_suggestions":"De tu lista","search":"Buscar acciones","watchlist":"Lista de seguimiento","provider":"Proveedor","language":"Idioma","refresh":"Actualizar","analyze":"Analizar","watch":"Seguir","remove":"Quitar","no_results":"No se encontraron valores.","scanner":"Escáner y recomendaciones","queue":"Ejecutar escáner","latest":"Último escaneo","confidence":"Confianza","reliability":"Fiabilidad","expected":"Rentabilidad prevista a 5 días","price":"Precio","change":"Cambio diario","save":"Guardar","identity":"Identidad","data_source":"Fuente de datos","auto":"Fallback automático","model":"Modelo de predicción","no_model":"Entrena e instala el modelo antes de usar predicciones."},
"it": {"home":"Home","stocks":"Azioni","discover":"Scopri","settings":"Impostazioni","market_pulse":"Mercato in tempo reale","top_stocks":"Azioni principali","discover_short":"Scopri","watch_suggestions":"Dalla tua lista","search":"Cerca azioni","watchlist":"Lista osservati","provider":"Provider","language":"Lingua","refresh":"Aggiorna","analyze":"Analizza","watch":"Segui","remove":"Rimuovi","no_results":"Nessun titolo trovato.","scanner":"Scanner e raccomandazioni","queue":"Avvia scanner","latest":"Ultima scansione","confidence":"Confidenza","reliability":"Affidabilità","expected":"Rendimento previsto a 5 giorni","price":"Prezzo","change":"Variazione giornaliera","save":"Salva","identity":"Identità","data_source":"Fonte dati","auto":"Fallback automatico","model":"Modello predittivo","no_model":"Addestra e installa il modello prima delle previsioni."},
"de": {"home":"Start","stocks":"Aktien","discover":"Entdecken","settings":"Einstellungen","market_pulse":"Live-Markt","top_stocks":"Top-Aktien","discover_short":"Entdecken","watch_suggestions":"Aus deiner Liste","search":"Aktien suchen","watchlist":"Beobachtungsliste","provider":"Datenanbieter","language":"Sprache","refresh":"Aktualisieren","analyze":"Analysieren","watch":"Beobachten","remove":"Entfernen","no_results":"Keine Wertpapiere gefunden.","scanner":"Scanner und Empfehlungen","queue":"Scanner starten","latest":"Letzter Scan","confidence":"Konfidenz","reliability":"Zuverlässigkeit","expected":"Erwartete 5-Tage-Rendite","price":"Preis","change":"Tagesänderung","save":"Speichern","identity":"Identität","data_source":"Datenquelle","auto":"Automatischer Fallback","model":"Prognosemodell","no_model":"Modell trainieren und installieren, bevor Prognosen verfügbar sind."},
"zh": {"home":"首页","stocks":"股票","discover":"发现","settings":"设置","market_pulse":"实时市场脉搏","top_stocks":"热门股票","discover_short":"发现","watch_suggestions":"自选股建议","search":"搜索股票","watchlist":"自选列表","provider":"数据源","language":"语言","refresh":"刷新","analyze":"分析","watch":"加入自选","remove":"移除","no_results":"未找到证券。","scanner":"扫描与推荐","queue":"运行扫描","latest":"最近扫描","confidence":"置信度","reliability":"可靠性","expected":"5日预期收益","price":"价格","change":"日涨跌","save":"保存设置","identity":"身份","data_source":"数据来源","auto":"自动回退","model":"预测模型","no_model":"请先训练并安装模型。"},
"ja": {"home":"ホーム","stocks":"銘柄","discover":"発見","settings":"設定","market_pulse":"ライブ市場","top_stocks":"注目銘柄","discover_short":"発見","watch_suggestions":"ウォッチリストから","search":"銘柄を検索","watchlist":"ウォッチリスト","provider":"プロバイダー","language":"言語","refresh":"更新","analyze":"分析","watch":"追加","remove":"削除","no_results":"証券が見つかりません。","scanner":"スキャナーとおすすめ","queue":"スキャン実行","latest":"最新スキャン","confidence":"信頼度","reliability":"信頼性","expected":"5日予想リターン","price":"価格","change":"日次変化","save":"設定を保存","identity":"ID","data_source":"データソース","auto":"自動フォールバック","model":"予測モデル","no_model":"予測前にモデルを学習・配置してください。"},
"ko": {"home":"홈","stocks":"종목","discover":"발견","settings":"설정","market_pulse":"실시간 시장","top_stocks":"주요 종목","discover_short":"발견","watch_suggestions":"관심종목 기반","search":"종목 검색","watchlist":"관심종목","provider":"데이터 제공자","language":"언어","refresh":"새로고침","analyze":"분석","watch":"추가","remove":"삭제","no_results":"증권을 찾을 수 없습니다.","scanner":"스캐너 및 추천","queue":"스캔 실행","latest":"최근 스캔","confidence":"신뢰도","reliability":"신뢰성","expected":"5일 예상 수익률","price":"가격","change":"일간 변동","save":"설정 저장","identity":"신원","data_source":"데이터 소스","auto":"자동 대체","model":"예측 모델","no_model":"예측 전에 모델을 학습하고 설치하세요."},
"pt": {"home":"Início","stocks":"Ações","discover":"Descobrir","settings":"Configurações","market_pulse":"Mercado ao vivo","top_stocks":"Ações em destaque","discover_short":"Descobrir","watch_suggestions":"Da sua lista","search":"Pesquisar ações","watchlist":"Lista de acompanhamento","provider":"Provedor","language":"Idioma","refresh":"Atualizar","analyze":"Analisar","watch":"Adicionar","remove":"Remover","no_results":"Nenhum título encontrado.","scanner":"Scanner e recomendações","queue":"Executar scanner","latest":"Última varredura","confidence":"Confiança","reliability":"Confiabilidade","expected":"Retorno esperado em 5 dias","price":"Preço","change":"Variação diária","save":"Salvar","identity":"Identidade","data_source":"Fonte de dados","auto":"Fallback automático","model":"Modelo de previsão","no_model":"Treine e instale o modelo antes das previsões."},
}

TEXT_EXTRAS = {
    "en": {"overview":"Market overview, saved symbols and model signals.","no_scan":"No completed scan yet.","scanner_caption":"Model-ranked signals from the current app session.","universe_size":"Universe size","scan_job":"Run scanner","storage_unavailable":"Persistent storage is unavailable.","job_status":"Job","top_by_area":"Top stocks by area","area":"Area","bullish_signals":"Bullish signals","sign_out":"Sign out","not_signed_in":"Not signed in.","settings_saved":"Settings saved.","select_stock":"Select a stock by clicking any stock card.","historical_unavailable":"Historical data is unavailable for this symbol.","price_history":"Price history","model_outlook":"Model outlook","forecast_note":"Model outlook is an estimate, not a guarantee."},
        "en": {"overview":"Market overview, saved symbols and model signals.","no_scan":"No completed scan yet.","scanner_caption":"Model-ranked signals from the current app session.","universe_size":"Universe size","scan_job":"Run scanner","storage_unavailable":"Persistent storage is unavailable.","job_status":"Job","top_by_area":"Top stocks by area","area":"Area","bullish_signals":"Bullish signals","sign_out":"Sign out","not_signed_in":"Not signed in.","settings_saved":"Settings saved.","select_stock":"Select a stock by clicking any stock card.","historical_unavailable":"Historical data is unavailable for this symbol.","price_history":"Price history","model_outlook":"Model outlook","forecast_note":"Model outlook is an estimate, not a guarantee.","prediction_data":"Prediction data is unavailable.","model_mismatch":"The trained model does not match the current feature set. Retrain it.","not_enough_history":"Not enough recent history for a 64-day prediction window.","prediction_unavailable":"Prediction unavailable","relevant_results":"relevant result(s)","search_watchlist":"Search for a symbol to add it to your watchlist.","area_top_stocks":"Top stocks","area_technology":"Technology","area_healthcare":"Healthcare","area_financials":"Financials","area_consumer":"Consumer","area_etfs":"ETFs"},
    "fr": {"overview":"Vue du marché, symboles enregistrés et signaux du modèle.","no_scan":"Aucun scan terminé.","scanner_caption":"Signaux classés par le modèle depuis le scanner.","universe_size":"Taille de l'univers","scan_job":"Scan ajouté à la file","storage_unavailable":"Stockage persistant indisponible.","job_status":"Tâche","top_by_area":"Meilleures actions par secteur","area":"Secteur","bullish_signals":"Signaux haussiers","sign_out":"Se déconnecter","not_signed_in":"Non connecté.","settings_saved":"Paramètres enregistrés.","select_stock":"Sélectionnez une action en cliquant sur une carte.","historical_unavailable":"Données historiques indisponibles.","price_history":"Historique des prix","model_outlook":"Prévision du modèle","forecast_note":"La prévision est une estimation, pas une garantie."},
    "es": {"overview":"Resumen del mercado, símbolos guardados y señales del modelo.","no_scan":"Aún no hay un escaneo completado.","scanner_caption":"Señales clasificadas por el modelo.","universe_size":"Tamaño del universo","scan_job":"Escaneo en cola","storage_unavailable":"Almacenamiento persistente no disponible.","job_status":"Trabajo","top_by_area":"Mejores acciones por área","area":"Área","bullish_signals":"Señales alcistas","sign_out":"Cerrar sesión","not_signed_in":"No has iniciado sesión.","settings_saved":"Configuración guardada.","select_stock":"Selecciona una acción haciendo clic en una tarjeta.","historical_unavailable":"Datos históricos no disponibles.","price_history":"Historial de precios","model_outlook":"Previsión del modelo","forecast_note":"La previsión es una estimación, no una garantía."},
    "de": {"overview":"Marktübersicht, gespeicherte Symbole und Modellsignale.","no_scan":"Noch kein Scan abgeschlossen.","scanner_caption":"Vom Scanner bewertete Modellsignale.","universe_size":"Universumsgröße","scan_job":"Scan eingereiht","storage_unavailable":"Dauerhafter Speicher nicht verfügbar.","job_status":"Aufgabe","top_by_area":"Top-Aktien nach Bereich","area":"Bereich","bullish_signals":"Bullische Signale","sign_out":"Abmelden","not_signed_in":"Nicht angemeldet.","settings_saved":"Einstellungen gespeichert.","select_stock":"Wähle eine Aktie durch Klicken auf eine Karte.","historical_unavailable":"Historische Daten nicht verfügbar.","price_history":"Kursverlauf","model_outlook":"Modellprognose","forecast_note":"Die Prognose ist eine Schätzung, keine Garantie."},
    "it": {"overview":"Panoramica del mercato, simboli salvati e segnali del modello.","no_scan":"Nessuna scansione completata.","scanner_caption":"Segnali classificati dal modello.","universe_size":"Dimensione universo","scan_job":"Scansione accodata","storage_unavailable":"Archiviazione persistente non disponibile.","job_status":"Processo","top_by_area":"Azioni principali per area","area":"Area","bullish_signals":"Segnali rialzisti","sign_out":"Esci","not_signed_in":"Non hai effettuato l'accesso.","settings_saved":"Impostazioni salvate.","select_stock":"Seleziona un'azione facendo clic su una scheda.","historical_unavailable":"Dati storici non disponibili.","price_history":"Storico prezzi","model_outlook":"Previsione del modello","forecast_note":"La previsione è una stima, non una garanzia."},
    "pt": {"overview":"Visão do mercado, símbolos guardados e sinais do modelo.","no_scan":"Nenhuma varredura concluída.","scanner_caption":"Sinais classificados pelo modelo.","universe_size":"Tamanho do universo","scan_job":"Varredura enfileirada","storage_unavailable":"Armazenamento persistente indisponível.","job_status":"Tarefa","top_by_area":"Principais ações por área","area":"Área","bullish_signals":"Sinais de alta","sign_out":"Sair","not_signed_in":"Não conectado.","settings_saved":"Configurações salvas.","select_stock":"Selecione uma ação clicando em um cartão.","historical_unavailable":"Dados históricos indisponíveis.","price_history":"Histórico de preços","model_outlook":"Previsão do modelo","forecast_note":"A previsão é uma estimativa, não uma garantia.","prediction_data":"Dados de previsão indisponíveis.","model_mismatch":"O modelo treinado não corresponde aos recursos atuais. Treine-o novamente.","not_enough_history":"Histórico recente insuficiente para uma previsão de 64 dias.","prediction_unavailable":"Previsão indisponível","relevant_results":"resultado(s) relevante(s)","search_watchlist":"Pesquise um símbolo para adicioná-lo à sua lista."},
    "zh": {"overview":"市场概览、已保存代码和模型信号。","no_scan":"尚未完成扫描。","scanner_caption":"来自持久扫描器的模型信号。","universe_size":"股票范围","scan_job":"扫描任务已排队","storage_unavailable":"持久存储不可用。","job_status":"任务","top_by_area":"各领域热门股票","area":"领域","bullish_signals":"看涨信号","sign_out":"退出登录","not_signed_in":"未登录。","settings_saved":"设置已保存。","select_stock":"点击股票卡片选择股票。","historical_unavailable":"历史数据不可用。","price_history":"价格历史","model_outlook":"模型预测","forecast_note":"模型预测仅供参考，并非保证。","prediction_data":"预测数据不可用。","model_mismatch":"训练模型与当前特征不匹配。请重新训练。","not_enough_history":"64天预测所需的历史数据不足。","prediction_unavailable":"预测不可用","relevant_results":"个相关结果","search_watchlist":"搜索代码以添加到自选列表。"},
    "ja": {"overview":"市場概要、保存した銘柄、モデルシグナル。","no_scan":"完了したスキャンはありません。","scanner_caption":"永続スキャナーによるモデルシグナル。","universe_size":"対象範囲","scan_job":"スキャンをキューに追加しました","storage_unavailable":"永続ストレージを利用できません。","job_status":"ジョブ","top_by_area":"分野別の注目銘柄","area":"分野","bullish_signals":"強気シグナル","sign_out":"サインアウト","not_signed_in":"未ログインです。","settings_saved":"設定を保存しました。","select_stock":"カードをクリックして銘柄を選択してください。","historical_unavailable":"履歴データを利用できません。","price_history":"価格履歴","model_outlook":"モデル予測","forecast_note":"モデル予測は推定であり、保証ではありません。","prediction_data":"予測データを利用できません。","model_mismatch":"学習済みモデルと現在の特徴量が一致しません。","not_enough_history":"64日予測に十分な履歴がありません。","prediction_unavailable":"予測を利用できません","relevant_results":"件の関連結果","search_watchlist":"銘柄を検索してウォッチリストに追加してください。"},
    "ko": {"overview":"시장 개요, 저장된 종목 및 모델 신호입니다.","no_scan":"완료된 스캔이 없습니다.","scanner_caption":"지속 스캐너의 모델 신호입니다.","universe_size":"대상 범위","scan_job":"스캔 작업이 대기열에 추가되었습니다","storage_unavailable":"영구 저장소를 사용할 수 없습니다.","job_status":"작업","top_by_area":"분야별 주요 종목","area":"분야","bullish_signals":"강세 신호","sign_out":"로그아웃","not_signed_in":"로그인하지 않았습니다.","settings_saved":"설정이 저장되었습니다.","select_stock":"카드를 클릭하여 종목을 선택하세요.","historical_unavailable":"과거 데이터를 사용할 수 없습니다.","price_history":"가격 기록","model_outlook":"모델 전망","forecast_note":"모델 전망은 추정치이며 보장되지 않습니다.","prediction_data":"예측 데이터를 사용할 수 없습니다.","model_mismatch":"학습 모델이 현재 특성과 일치하지 않습니다.","not_enough_history":"64일 예측에 필요한 기록이 부족합니다.","prediction_unavailable":"예측을 사용할 수 없습니다","relevant_results":"개의 관련 결과","search_watchlist":"종목을 검색하여 관심 목록에 추가하세요."},
}
for _language, _values in TEXT_EXTRAS.items():
    TEXT.setdefault(_language, {}).update(_values)

AREA_LABELS = {
    "fr": {"area_top_stocks":"Actions principales","area_technology":"Technologie","area_healthcare":"Santé","area_financials":"Finance","area_consumer":"Consommation","area_etfs":"ETF"},
    "es": {"area_top_stocks":"Acciones principales","area_technology":"Tecnología","area_healthcare":"Salud","area_financials":"Finanzas","area_consumer":"Consumo","area_etfs":"ETF"},
    "it": {"area_top_stocks":"Azioni principali","area_technology":"Tecnologia","area_healthcare":"Sanità","area_financials":"Finanza","area_consumer":"Consumi","area_etfs":"ETF"},
    "de": {"area_top_stocks":"Top-Aktien","area_technology":"Technologie","area_healthcare":"Gesundheit","area_financials":"Finanzen","area_consumer":"Konsum","area_etfs":"ETFs"},
    "pt": {"area_top_stocks":"Principais ações","area_technology":"Tecnologia","area_healthcare":"Saúde","area_financials":"Finanças","area_consumer":"Consumo","area_etfs":"ETFs"},
    "zh": {"area_top_stocks":"热门股票","area_technology":"科技","area_healthcare":"医疗保健","area_financials":"金融","area_consumer":"消费","area_etfs":"交易所交易基金"},
    "ja": {"area_top_stocks":"注目銘柄","area_technology":"テクノロジー","area_healthcare":"ヘルスケア","area_financials":"金融","area_consumer":"消費関連","area_etfs":"ETF"},
    "ko": {"area_top_stocks":"주요 종목","area_technology":"기술","area_healthcare":"헬스케어","area_financials":"금융","area_consumer":"소비재","area_etfs":"ETF"},
}
for _language, _values in AREA_LABELS.items():
    TEXT[_language].update(_values)

TEXT["fr"]["prediction_data"] = "Données de prévision indisponibles."
TEXT["es"]["prediction_data"] = "Datos de predicción no disponibles."
TEXT["it"]["prediction_data"] = "Dati di previsione non disponibili."
TEXT["de"]["prediction_data"] = "Prognosedaten nicht verfügbar."
TEXT["fr"]["search_watchlist"] = "Recherchez un symbole pour l'ajouter à votre liste."
TEXT["es"]["search_watchlist"] = "Busca un símbolo para añadirlo a tu lista."
TEXT["it"]["search_watchlist"] = "Cerca un simbolo per aggiungerlo alla lista."
TEXT["de"]["search_watchlist"] = "Suche ein Symbol, um es deiner Liste hinzuzufügen."

def secret(name, default=None):
    try: return st.secrets.get(name, default)
    except Exception: return os.getenv(name, default)

def database_url():
    direct = secret("database_url") or os.getenv("DATABASE_URL")
    if direct: return str(direct).strip()
    try:
        pg=st.secrets.get("connections",{}).get("postgresql",{})
        if pg:
            from urllib.parse import quote_plus
            return f"postgresql+psycopg://{quote_plus(str(pg['username']))}:{quote_plus(str(pg['password']))}@{pg['host']}:{pg.get('port',5432)}/{pg['database']}"
    except Exception: pass
    return None

def require_auth():
    v=secret("require_auth",False)
    return str(v).lower() in {"1","true","yes","on"} if isinstance(v,str) else bool(v)
